import os
import re
import logging
from fpdf import FPDF

logger = logging.getLogger("agentflow.pdf_generator")

class ExecutiveReportPDF(FPDF):
    """
    Custom FPDF template with headers, footers, page numbering,
    and a sleek modern design suited for corporate operations reports.
    """
    def header(self):
        # Top brand layout
        self.set_fill_color(15, 15, 18) # Dark dark charcoal header
        self.rect(0, 0, 210, 25, "F")
        
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 11)
        self.cell(0, 10, "AGENTFLOW AI - WORKSPACE PERFORMANCE REPORT", ln=True, align="L")
        
        # Subtle horizontal divider line
        self.set_draw_color(168, 85, 247) # Neon purple line accent
        self.set_line_width(0.8)
        self.line(10, 24, 200, 24)
        self.ln(10)

    def footer(self):
        # Footer branding
        self.set_y(-15)
        self.set_draw_color(230, 230, 230)
        self.set_line_width(0.2)
        self.line(10, self.get_y() - 2, 200, self.get_y() - 2)
        
        self.set_text_color(120, 120, 120)
        self.set_font("Helvetica", "I", 8)
        self.cell(0, 10, f"Confidential | Page {self.page_no()}", align="R")
        self.cell(0, 10, "Generated by AgentFlow Multi-Agent Pipeline", align="L")

def generate_report_pdf(markdown_content: str, output_path: str) -> str:
    """
    Compiles unstructured Markdown report logs into a styled PDF.
    """
    pdf = ExecutiveReportPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    pdf.set_margins(15, 25, 15)
    
    # Body font
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(40, 40, 42)
    
    lines = markdown_content.split("\n")
    for line in lines:
        line = line.strip()
        if not line:
            pdf.ln(4)
            continue
            
        # Parse titles
        if line.startswith("# "):
            title = line[2:]
            pdf.set_font("Helvetica", "B", 18)
            pdf.set_text_color(15, 15, 18)
            pdf.ln(6)
            pdf.cell(0, 10, title, ln=True)
            pdf.ln(4)
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(40, 40, 42)
        elif line.startswith("## "):
            subtitle = line[3:]
            pdf.set_font("Helvetica", "B", 14)
            pdf.set_text_color(168, 85, 247) # Accent color (purple)
            pdf.ln(4)
            pdf.cell(0, 8, subtitle, ln=True)
            pdf.ln(2)
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(40, 40, 42)
        elif line.startswith("### "):
            section = line[4:]
            pdf.set_font("Helvetica", "B", 12)
            pdf.set_text_color(50, 50, 50)
            pdf.ln(3)
            pdf.cell(0, 6, section, ln=True)
            pdf.ln(2)
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(40, 40, 42)
        # Parse lists
        elif line.startswith("- ") or line.startswith("* "):
            item = line[2:]
            # Clean strong bold markup like **text**
            clean_item = re.sub(r"\*\*(.*?)\*\*", r"\1", item)
            pdf.set_font("Helvetica", "", 10)
            pdf.cell(6, 6, chr(149), align="R") # bullet character
            pdf.multi_cell(0, 6, f" {clean_item}")
        elif re.match(r"^\d+\.\s", line):
            # Numbered lists
            match = re.match(r"^(\d+)\.\s(.*)", line)
            num = match.group(1)
            item = match.group(2)
            clean_item = re.sub(r"\*\*(.*?)\*\*", r"\1", item)
            pdf.multi_cell(0, 6, f"  {num}. {clean_item}")
        else:
            # Clean bold text markup
            clean_text = re.sub(r"\*\*(.*?)\*\*", r"\1", line)
            pdf.multi_cell(0, 6, clean_text)
            
    try:
        pdf.output(output_path)
        logger.info(f"PDF report successfully exported to '{output_path}'.")
        return output_path
    except Exception as e:
        logger.error(f"Failed to generate PDF output file: {e}")
        raise e
